.IGNORE:all
all:
	gcc hw0501.c -lm -o hw0501
	gcc hw0502.c -lm -o hw0502
	gcc hw0503.c -lm -o hw0503
	gcc hw0504.c -lm -o hw0504
%.o:%.c
	gcc -c $< -o $@
clean:
	rm -rf hw0501 hw0502 hw0503 hw0504 *.o

